"""Generate the state-only / state+RGB arm configs and PROVE they are one-variable pairs.

The campaign asks whether adding a camera to a skill actor that already has the
state helps. That is only answerable if the two arms differ in exactly one thing.
Hand-written configs cannot guarantee that -- the existing cartpole state and RGB
configs differ in LR (3e-4 vs 1e-4), NUM_MINIBATCHES (32 vs 8), ACTOR_HIDDEN_SIZES
([128,128] vs [256,256]) and PLAYGROUND_IMPL as well as the RGB keys -- so both
arms are DERIVED HERE from a single per-env base and the difference is asserted.

Base config per env = the config the committed pixels-only ("blind") arm used, so
each env ends up with a three-point ladder that varies only the ACTOR's input:

    RGB_PROPRIO: none  + RGB_ACTOR: true    pixels only      (already committed)
    RGB_PROPRIO: full  + RGB_ACTOR: true    state + pixels   (new)
    RGB_PROPRIO: full  + RGB_ACTOR: false   state only       (new)

RGB_PROPRIO is left at "full" in BOTH new arms on purpose: it is inert when
RGB_ACTOR is false (the trainer never calls `_actor_proprio` on the state path),
so the two emitted files differ by exactly one line, `RGB_ACTOR`.

    python tools/gen_state_plus_rgb_configs.py            # write + verify
    python tools/gen_state_plus_rgb_configs.py --check    # verify only
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# env -> (base config, output stem). The base is the config the committed
# pixels-only arm for that env was trained with, so the new arms slot straight
# into the existing results as a controlled ladder.
ENVS = {
    "cartpole": ("configs/cartpole_balance_nesy_rgb.yaml", "cartpole_balance_nesy"),
    "walker": ("configs/walker_walk_nesy.yaml", "walker_walk_nesy"),
    "cheetah": ("configs/cheetah_run_nesy.yaml", "cheetah_run_nesy"),
}

# Applied identically to BOTH arms, so none of them can confound the comparison.
# Every one is either already the base's value or a documented no-op.
SHARED = {
    "USE_RGB": True,            # the ENV renders in both arms (see below)
    "RGB_EPISODE_LENGTH": 250,  # explicit; 250 is also the default and cartpole forces it
    "RGB_EMBED_DIM": 128,
    "RGB_AUGMENT": True,
    "RGB_AUG_PAD": 4,
    "RGB_PROPRIO": "full",      # inert when RGB_ACTOR is false
    "META_POLICY_TYPE": "nesy",
    "NUM_ENVS": 128,
    "NUM_STEPS": 64,
    "NUM_SEEDS": 1,
    "SEED": 0,
    "TOTAL_TIMESTEPS": 2048000,  # 128 envs x 64 steps x 250 updates
}

# THE one variable.
ARMS = {"state_plus_rgb": True, "state_matched": False}

# Phase 2: CheetahRun and WalkerWalk at the full 52.4M-step budget. BOTH arms
# keep 128 envs and take 6400 updates, so they match on gradient steps and batch
# size as well as on environment steps. (The tempting alternative -- state at its
# canonical 2048 envs x 400 updates and RGB at 128 envs x 6400 -- matches env
# steps only, and hands the RGB arm 16x more gradient steps at 1/16 the batch
# size, which would make any difference uninterpretable.)
#
# WalkerWalk is the env where the matched budget favoured the extension: training
# return 189.51 +/- 1.80 -> 203.20 +/- 6.25 (+7.2%, 3/3 seeds, non-overlapping),
# 30-episode eval 0.713 -> 0.816, and the only env where the actor demonstrably
# used the camera (frozen_first costs 62-72%). Running it at 25.6x the budget
# asks whether that advantage survives training to convergence or is a
# small-budget optimisation artefact.
FULL = {
    "envs": ["cheetah", "walker"],
    "updates": 6400,
    "overrides": {
        "TOTAL_TIMESTEPS": 52428800,   # 128 x 64 x 6400
        # Progress must survive a kill: an ~8h job on a shared GPU can be
        # interrupted, and the ablation script only writes training_curves.json
        # at the end. env_step advances by NUM_ENVS*NUM_STEPS = 8192 per update,
        # so 409600 prints a live line every 50 updates into the run log.
        "PRINT_EVERY": 409600,
    },
}

HEADER = """\
# GENERATED by tools/gen_state_plus_rgb_configs.py -- DO NOT EDIT BY HAND.
#
# {arm_title}
# Environment: {env}     base config: {base}
#
# WHY THE ENVIRONMENT KEEPS USE_RGB: true IN BOTH ARMS
# ----------------------------------------------------
# USE_RGB does not only change the actor, it changes the TASK. MuJoCo
# Playground's CartpoleBalance keys ctrl_dt, episode_length, the reward function
# (_dense_vision_reward vs _dense_reward) and the termination rule on `vision`;
# for Walker/Cheetah the adapter swaps in the ported VISION_ENVS subclasses at
# impl="warp"; and the vec wrapper feeds the actor qpos+qvel in vision mode but
# the DM-suite featurised observation otherwise. A `USE_RGB: false` baseline
# would therefore differ in the environment, the reward, the horizon, the
# physics backend AND the state representation -- everything except the one
# variable under test.
#
# So both arms keep the identical vision ENVIRONMENT and differ only in
# RGB_ACTOR, which gates whether the skill ACTORS have a camera pathway:
#
#   RGB_ACTOR: true   actor(pixels, state) -- state + RGB
#   RGB_ACTOR: false  actor(state)         -- state only, matched budget
#
# RGB_PROPRIO stays "full" in both files because it is inert on the state path,
# which makes the diff between the two arms exactly one line.
#
# Budget (both arms, and the committed pixels-only arm): 250 updates x 128 envs
# x 64 steps = 2,048,000 environment steps.
{extra}"""

EXTRA = {
    "cartpole": (
        "#\n"
        "# NOTE (reported, not fixed): this base carries NUM_MINIBATCHES: 8, while the\n"
        "# walker and cheetah bases use 64 -- cartpole therefore takes 8x fewer\n"
        "# gradient steps at the same environment-step budget. It is IDENTICAL in\n"
        "# both arms, so it cannot confound state-vs-state+RGB; it only means\n"
        "# cartpole numbers are not comparable ACROSS envs.\n"
    ),
    "walker": "",
    "cheetah": "",
}

TITLES = {
    "state_plus_rgb": "STATE + RGB arm: the skill actors read the privileged state AND the camera.",
    "state_matched": "STATE-ONLY arm: matched-budget control; the skill actors read the state only.",
}


def main(argv=None):
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="repo root")
    ap.add_argument("--outdir", default="configs")
    ap.add_argument("--check", action="store_true", help="verify only, write nothing")
    args = ap.parse_args(argv)

    import yaml

    sys.path.insert(0, str(Path(args.root).resolve()))
    from nexus_continuous.utils import load_config

    root = Path(args.root)
    outdir = root / args.outdir
    written, failures = [], []

    for env, (base_rel, stem) in ENVS.items():
        base_path = root / base_rel
        base = yaml.safe_load(base_path.read_text())
        paths = {}
        for arm, rgb_actor in ARMS.items():
            cfg = dict(base)
            cfg.update(SHARED)
            cfg["RGB_ACTOR"] = rgb_actor
            path = outdir / f"{stem}_{arm}.yaml"
            text = HEADER.format(arm_title=TITLES[arm], env=env, base=base_rel,
                                 extra=EXTRA[env]) + yaml.safe_dump(cfg, sort_keys=True)
            if not args.check:
                path.write_text(text)
                written.append(path)
            paths[arm] = path

        # ---- machine verification: resolved configs differ ONLY in RGB_ACTOR ----
        a = load_config(paths["state_matched"])
        b = load_config(paths["state_plus_rgb"])
        keys = set(a) | set(b)
        diff = {k: (a.get(k, "<absent>"), b.get(k, "<absent>"))
                for k in keys if a.get(k, "<absent>") != b.get(k, "<absent>")}
        ok = set(diff) == {"RGB_ACTOR"}
        print(f"\n=== {env}  (base {base_rel}) ===")
        print(f"  state_matched : {paths['state_matched']}")
        print(f"  state_plus_rgb: {paths['state_plus_rgb']}")
        print(f"  resolved-config diff (state_matched -> state_plus_rgb):")
        for k, (va, vb) in sorted(diff.items()):
            print(f"      {k}: {va!r} -> {vb!r}")
        print(f"  ONE-VARIABLE PAIR: {'YES' if ok else 'NO'}")
        if not ok:
            failures.append(env)

        # ---- how each arm differs from its base, for the report ----
        for arm in ARMS:
            c = load_config(paths[arm])
            d = {k: (base.get(k, "<absent>"), c.get(k, "<absent>"))
                 for k in set(base) | set(c)
                 if base.get(k, "<absent>") != c.get(k, "<absent>")}
            print(f"  {arm} vs base: " + ", ".join(
                f"{k}: {va!r}->{vb!r}" for k, (va, vb) in sorted(d.items())) or "  (identical)")

    # ---------------- phase 2: full-budget arms (same one-variable guarantee) ----
    for env in FULL["envs"]:
        base_rel, stem = ENVS[env]
        base = yaml.safe_load((root / base_rel).read_text())
        paths = {}
        for arm, rgb_actor in ARMS.items():
            cfg = dict(base)
            cfg.update(SHARED)
            cfg.update(FULL["overrides"])
            cfg["RGB_ACTOR"] = rgb_actor
            name = "state_plus_rgb_full" if arm == "state_plus_rgb" else "state_matched_full"
            path = outdir / f"{stem}_{name}.yaml"
            extra = EXTRA[env] + (
                "#\n"
                f"# PHASE 2 -- FULL BUDGET: {FULL['updates']} updates x 128 envs x 64 steps\n"
                f"# = {FULL['overrides']['TOTAL_TIMESTEPS']:,} environment steps (25.6x the\n"
                "# matched-budget arms). BOTH arms run at 128 envs and 6400 updates, so they\n"
                "# match on gradient steps and batch size too, not just on env steps.\n")
            text = HEADER.format(arm_title=TITLES[arm], env=env, base=base_rel,
                                 extra=extra) + yaml.safe_dump(cfg, sort_keys=True)
            if not args.check:
                path.write_text(text)
                written.append(path)
            paths[arm] = path
        a = load_config(paths["state_matched"])
        b = load_config(paths["state_plus_rgb"])
        diff = {k: (a.get(k, "<absent>"), b.get(k, "<absent>"))
                for k in set(a) | set(b) if a.get(k, "<absent>") != b.get(k, "<absent>")}
        ok = set(diff) == {"RGB_ACTOR"}
        print(f"\n=== {env} FULL BUDGET (base {base_rel}) ===")
        print(f"  state_matched_full : {paths['state_matched']}")
        print(f"  state_plus_rgb_full: {paths['state_plus_rgb']}")
        print("  resolved-config diff:")
        for k, (va, vb) in sorted(diff.items()):
            print(f"      {k}: {va!r} -> {vb!r}")
        print(f"  ONE-VARIABLE PAIR: {'YES' if ok else 'NO'}")
        if not ok:
            failures.append(env + "_full")

    if written:
        print(f"\nwrote {len(written)} config(s)")
    if failures:
        raise SystemExit(f"FAILED one-variable check for: {failures}")
    print("\nAll pairs verified one-variable (RGB_ACTOR only).")


if __name__ == "__main__":
    main()
